# ─── AI Stack Local ─────────────────────────────────
# Separado del compose principal para poder levantar/apagar
# la IA sin afectar la base de datos y servicios core.
#
# Uso: docker compose -f ai-stack.yml up -d
# ─────────────────────────────────────────────────────

version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 8G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    ports:
      - "8880:8880"
    deploy:
      resources:
        limits:
          memory: 1G

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "9900:9000"
    environment:
      ASR_MODEL: base
      ASR_ENGINE: openai_whisper
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  ollama_data:
